// Enterprise-grade mock data for Helpdesk SaaS

export const CURRENT_USER = {
  id: "usr_4f8a",
  name: "Helena Marques",
  email: "helena.marques@crjsystems.com",
  role: "Support Specialist (Tier 2)",
  permissions: ["read:tickets", "write:tickets", "read:customers", "write:notes"],
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?crop=entropy&cs=srgb&fm=jpg&w=128&q=80",
  initials: "HM",
  tier: 2,
};

export const AGENTS = [
  { id: "ag_01", name: "Helena Marques", initials: "HM", tier: 2, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?crop=entropy&cs=srgb&fm=jpg&w=64&q=80" },
  { id: "ag_02", name: "Rafael Costa", initials: "RC", tier: 3, avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&w=64&q=80" },
  { id: "ag_03", name: "Júlia Andrade", initials: "JA", tier: 1, avatar: "https://images.unsplash.com/photo-1607503873903-c5e95f80d7b9?crop=entropy&cs=srgb&fm=jpg&w=64&q=80" },
  { id: "ag_04", name: "Bruno Lima", initials: "BL", tier: 2, avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&w=64&q=80" },
];

export const CUSTOMERS = [
  { id: "c_001", name: "Mariana Sousa", company: "Crivo Pagamentos", email: "mariana.sousa@crivo.com.br", phone: "+55 (11) 97777-1284", cpf: "412.889.330-21", plan: "Enterprise", mrr: 4200, since: "2023-04-12", avatar: AGENTS[0].avatar },
  { id: "c_002", name: "Eduardo Tavares", company: "Lumen Health", email: "eduardo.tavares@lumenhealth.io", phone: "+55 (21) 98801-4477", cpf: "098.221.110-43", plan: "Growth", mrr: 1280, since: "2024-01-08", avatar: AGENTS[3].avatar },
  { id: "c_003", name: "Patricia Veloso", company: "Northbeam Logistics", email: "p.veloso@northbeam.co", phone: "+55 (11) 99412-7765", cpf: "554.776.220-09", plan: "Enterprise", mrr: 5800, since: "2022-11-30", avatar: AGENTS[2].avatar },
  { id: "c_004", name: "Marcos Aurelio", company: "Vox Analytics", email: "marcos@voxanalytics.com", phone: "+55 (31) 98321-0099", cpf: "770.114.882-11", plan: "Starter", mrr: 320, since: "2025-03-14", avatar: AGENTS[1].avatar },
  { id: "c_005", name: "Sophia Reyes", company: "Helix Robotics", email: "sophia.reyes@helixrobotics.com", phone: "+55 (11) 99887-3344", cpf: "112.443.665-87", plan: "Growth", mrr: 1840, since: "2024-09-22", avatar: AGENTS[0].avatar },
  { id: "c_006", name: "Daniel Pereira", company: "Atlas Banking", email: "daniel.pereira@atlasbank.com.br", phone: "+55 (11) 97234-5511", cpf: "300.998.221-44", plan: "Enterprise", mrr: 7200, since: "2021-06-18", avatar: AGENTS[3].avatar },
  { id: "c_007", name: "Camila Borges", company: "Verdant Energy", email: "camila.borges@verdant.eco", phone: "+55 (51) 99102-8821", cpf: "881.220.554-09", plan: "Growth", mrr: 1620, since: "2024-05-02", avatar: AGENTS[2].avatar },
  { id: "c_008", name: "Lucas Ribeiro", company: "Cortex AI", email: "lucas.ribeiro@cortexai.com", phone: "+55 (11) 98112-3490", cpf: "445.221.778-32", plan: "Enterprise", mrr: 6450, since: "2023-08-19", avatar: AGENTS[1].avatar },
];

const ago = (mins) => new Date(Date.now() - mins * 60_000).toISOString();

export const TICKETS = [
  {
    id: "TCK-2841",
    subject: "API Authentication Timeout on Crivo Gateway",
    customerId: "c_001",
    priority: "High",
    status: "In Progress",
    assignedTo: "ag_01",
    createdAt: ago(140),
    updatedAt: ago(12),
    sla: { breached: true, dueIn: -22 },
    channel: "Email",
    category: "Integration",
    description: "Recurrent 504 timeouts on /v2/auth across staging and production. Started after our 14:02 UTC deploy. Affects ~38% of card-present requests.",
    history: [
      { id: "h1", actor: "Mariana Sousa", actorType: "customer", action: "Ticket opened via email", at: ago(140) },
      { id: "h2", actor: "System", actorType: "system", action: "Auto-triaged → Integration · High priority", at: ago(139) },
      { id: "h3", actor: "Júlia Andrade", actorType: "agent", action: "Assigned to Helena Marques (Tier 2)", at: ago(120) },
      { id: "h4", actor: "System", actorType: "system", action: "SLA breach trigger — priority raised", at: ago(60) },
      { id: "h5", actor: "Helena Marques", actorType: "agent", action: "Replied with diagnostic request", at: ago(45) },
      { id: "h6", actor: "Mariana Sousa", actorType: "customer", action: "Attached HAR logs (3.2 MB)", at: ago(20) },
      { id: "h7", actor: "Helena Marques", actorType: "agent", action: "Status changed → In Progress", at: ago(12) },
    ],
    notes: [
      { id: "n1", author: "Helena Marques", at: ago(40), body: "HAR logs confirm 504 originates from auth-edge-2. Suspect token refresh loop." },
      { id: "n2", author: "Rafael Costa", at: ago(18), body: "Confirmed with infra: edge node degraded. Rolling restart scheduled in 5 min." },
    ],
  },
  {
    id: "TCK-2840",
    subject: "Webhook signature mismatch after key rotation",
    customerId: "c_006",
    priority: "High",
    status: "Open",
    assignedTo: "ag_02",
    createdAt: ago(95),
    updatedAt: ago(40),
    sla: { breached: false, dueIn: 18 },
    channel: "API",
    category: "Security",
    description: "Webhooks failing HMAC verification on /payouts.completed. Customer rotated API keys at 09:15.",
    history: [
      { id: "h1", actor: "Daniel Pereira", actorType: "customer", action: "Ticket opened via API", at: ago(95) },
      { id: "h2", actor: "System", actorType: "system", action: "Auto-triaged → Security · High priority", at: ago(94) },
      { id: "h3", actor: "Rafael Costa", actorType: "agent", action: "Self-assigned", at: ago(80) },
    ],
    notes: [],
  },
  {
    id: "TCK-2839",
    subject: "Bulk export CSV missing column mapping",
    customerId: "c_003",
    priority: "Medium",
    status: "Pending",
    assignedTo: "ag_03",
    createdAt: ago(360),
    updatedAt: ago(180),
    sla: { breached: false, dueIn: 240 },
    channel: "In-app",
    category: "Data",
    description: "Export job completes but `customer_external_ref` column is omitted in the CSV.",
    history: [
      { id: "h1", actor: "Patricia Veloso", actorType: "customer", action: "Ticket opened via in-app form", at: ago(360) },
      { id: "h2", actor: "System", actorType: "system", action: "Auto-triaged → Data · Medium priority", at: ago(359) },
      { id: "h3", actor: "Júlia Andrade", actorType: "agent", action: "Status changed → Pending (awaiting eng)", at: ago(180) },
    ],
    notes: [],
  },
  {
    id: "TCK-2838",
    subject: "Onboarding link expired before activation",
    customerId: "c_004",
    priority: "Low",
    status: "Resolved",
    assignedTo: "ag_03",
    createdAt: ago(1440),
    updatedAt: ago(720),
    sla: { breached: false, dueIn: 0 },
    channel: "Email",
    category: "Account",
    description: "Customer's onboarding magic link expired after 24h window.",
    history: [
      { id: "h1", actor: "Marcos Aurelio", actorType: "customer", action: "Ticket opened via email", at: ago(1440) },
      { id: "h2", actor: "Júlia Andrade", actorType: "agent", action: "Reissued link", at: ago(900) },
      { id: "h3", actor: "Júlia Andrade", actorType: "agent", action: "Status changed → Resolved", at: ago(720) },
    ],
    notes: [],
  },
  {
    id: "TCK-2837",
    subject: "Dashboard widgets not rendering on Safari 18",
    customerId: "c_005",
    priority: "Medium",
    status: "In Progress",
    assignedTo: "ag_04",
    createdAt: ago(240),
    updatedAt: ago(60),
    sla: { breached: false, dueIn: 80 },
    channel: "Chat",
    category: "Frontend",
    description: "Charts on /analytics fail to render — console shows ResizeObserver loop limit exceeded.",
    history: [
      { id: "h1", actor: "Sophia Reyes", actorType: "customer", action: "Ticket opened via chat", at: ago(240) },
      { id: "h2", actor: "Bruno Lima", actorType: "agent", action: "Self-assigned", at: ago(220) },
      { id: "h3", actor: "Bruno Lima", actorType: "agent", action: "Reproduced on Safari 18.1", at: ago(60) },
    ],
    notes: [],
  },
  {
    id: "TCK-2836",
    subject: "Invoice PDF rendering missing tax breakdown",
    customerId: "c_002",
    priority: "Low",
    status: "Open",
    assignedTo: "ag_03",
    createdAt: ago(420),
    updatedAt: ago(300),
    sla: { breached: false, dueIn: 320 },
    channel: "Email",
    category: "Billing",
    description: "Tax line items missing on PDFs generated after the 02/07 release.",
    history: [
      { id: "h1", actor: "Eduardo Tavares", actorType: "customer", action: "Ticket opened via email", at: ago(420) },
      { id: "h2", actor: "System", actorType: "system", action: "Auto-triaged → Billing · Low priority", at: ago(419) },
    ],
    notes: [],
  },
  {
    id: "TCK-2835",
    subject: "SSO SAML assertion rejected (InvalidNameIDPolicy)",
    customerId: "c_008",
    priority: "High",
    status: "In Progress",
    assignedTo: "ag_01",
    createdAt: ago(180),
    updatedAt: ago(30),
    sla: { breached: true, dueIn: -10 },
    channel: "Email",
    category: "Security",
    description: "Okta SAML assertion rejected for ~120 users post IdP metadata refresh.",
    history: [
      { id: "h1", actor: "Lucas Ribeiro", actorType: "customer", action: "Ticket opened via email", at: ago(180) },
      { id: "h2", actor: "System", actorType: "system", action: "Auto-triaged → Security · High priority", at: ago(180) },
      { id: "h3", actor: "Helena Marques", actorType: "agent", action: "Self-assigned", at: ago(150) },
      { id: "h4", actor: "System", actorType: "system", action: "SLA breach trigger — priority raised", at: ago(30) },
    ],
    notes: [],
  },
  {
    id: "TCK-2834",
    subject: "Rate limit higher than contract — 429 spikes",
    customerId: "c_007",
    priority: "Medium",
    status: "Open",
    assignedTo: "ag_02",
    createdAt: ago(500),
    updatedAt: ago(310),
    sla: { breached: false, dueIn: 160 },
    channel: "API",
    category: "Integration",
    description: "Receiving 429 at 480 req/min — contract states 600 req/min ceiling.",
    history: [
      { id: "h1", actor: "Camila Borges", actorType: "customer", action: "Ticket opened via API", at: ago(500) },
      { id: "h2", actor: "Rafael Costa", actorType: "agent", action: "Acknowledged — investigating", at: ago(310) },
    ],
    notes: [],
  },
  {
    id: "TCK-2833",
    subject: "Two-factor recovery code rejected",
    customerId: "c_005",
    priority: "Low",
    status: "Pending",
    assignedTo: "ag_04",
    createdAt: ago(720),
    updatedAt: ago(420),
    sla: { breached: false, dueIn: 60 },
    channel: "Email",
    category: "Account",
    description: "Recovery code returns 'expired' although issued yesterday.",
    history: [
      { id: "h1", actor: "Sophia Reyes", actorType: "customer", action: "Ticket opened via email", at: ago(720) },
      { id: "h2", actor: "Bruno Lima", actorType: "agent", action: "Requested account ID + last login IP", at: ago(420) },
    ],
    notes: [],
  },
  {
    id: "TCK-2832",
    subject: "Slack alerts firing twice per event",
    customerId: "c_001",
    priority: "Low",
    status: "Resolved",
    assignedTo: "ag_02",
    createdAt: ago(2880),
    updatedAt: ago(1440),
    sla: { breached: false, dueIn: 0 },
    channel: "In-app",
    category: "Integration",
    description: "Duplicate Slack alerts after enabling new alert channel.",
    history: [
      { id: "h1", actor: "Mariana Sousa", actorType: "customer", action: "Ticket opened via in-app", at: ago(2880) },
      { id: "h2", actor: "Rafael Costa", actorType: "agent", action: "Disabled legacy channel — status Resolved", at: ago(1440) },
    ],
    notes: [],
  },
  {
    id: "TCK-2831",
    subject: "Audit log export blocked for non-admin",
    customerId: "c_006",
    priority: "Medium",
    status: "In Progress",
    assignedTo: "ag_01",
    createdAt: ago(300),
    updatedAt: ago(80),
    sla: { breached: false, dueIn: 140 },
    channel: "Email",
    category: "Security",
    description: "Compliance officer cannot export audit logs — expected per LGPD article 9.",
    history: [
      { id: "h1", actor: "Daniel Pereira", actorType: "customer", action: "Ticket opened via email", at: ago(300) },
      { id: "h2", actor: "Helena Marques", actorType: "agent", action: "Self-assigned", at: ago(270) },
      { id: "h3", actor: "Helena Marques", actorType: "agent", action: "Escalated to Security team", at: ago(80) },
    ],
    notes: [],
  },
  {
    id: "TCK-2830",
    subject: "Mobile push notifications stopped on iOS 18.2",
    customerId: "c_004",
    priority: "Low",
    status: "Open",
    assignedTo: "ag_03",
    createdAt: ago(180),
    updatedAt: ago(120),
    sla: { breached: false, dueIn: 380 },
    channel: "Chat",
    category: "Frontend",
    description: "After iOS 18.2 update, push notifications stop after ~6 hours.",
    history: [
      { id: "h1", actor: "Marcos Aurelio", actorType: "customer", action: "Ticket opened via chat", at: ago(180) },
      { id: "h2", actor: "System", actorType: "system", action: "Auto-triaged → Frontend · Low priority", at: ago(180) },
    ],
    notes: [],
  },
];

// Ticket volume by day (last 14 days) — by priority
export const TICKET_TRENDS = [
  { day: "Jan 24", High: 4, Medium: 9, Low: 12 },
  { day: "Jan 25", High: 3, Medium: 8, Low: 14 },
  { day: "Jan 26", High: 5, Medium: 11, Low: 10 },
  { day: "Jan 27", High: 6, Medium: 10, Low: 13 },
  { day: "Jan 28", High: 4, Medium: 12, Low: 11 },
  { day: "Jan 29", High: 7, Medium: 9, Low: 9 },
  { day: "Jan 30", High: 5, Medium: 14, Low: 12 },
  { day: "Jan 31", High: 6, Medium: 11, Low: 15 },
  { day: "Feb 01", High: 8, Medium: 10, Low: 13 },
  { day: "Feb 02", High: 5, Medium: 13, Low: 14 },
  { day: "Feb 03", High: 7, Medium: 12, Low: 11 },
  { day: "Feb 04", High: 6, Medium: 15, Low: 13 },
  { day: "Feb 05", High: 9, Medium: 11, Low: 16 },
  { day: "Feb 06", High: 8, Medium: 13, Low: 14 },
];

export const KPIS = {
  activeTickets: { value: 12, breached: 4, moM: 8, direction: "up" },
  firstResponseMin: { value: 14.2, moM: -3, direction: "down" },
  csat: { value: 4.8, ceiling: 5.0, moM: 2.1, direction: "up" },
  resolutionRate: { value: 92, moM: 1.4, direction: "up" },
};

export const AUDIT_EVENTS = [
  { id: "ev_1", at: ago(3), actor: "helena.marques@crjsystems.com", event: "ticket.viewed", target: "TCK-2841", ip: "189.122.04.11", severity: "info" },
  { id: "ev_2", at: ago(8), actor: "system", event: "sla.breach.trigger", target: "TCK-2835", ip: "—", severity: "warning" },
  { id: "ev_3", at: ago(14), actor: "rafael.costa@crjsystems.com", event: "api_key.rotated", target: "key_prod_a8x", ip: "189.122.04.34", severity: "warning" },
  { id: "ev_4", at: ago(22), actor: "helena.marques@crjsystems.com", event: "ticket.status.changed", target: "TCK-2841 → In Progress", ip: "189.122.04.11", severity: "info" },
  { id: "ev_5", at: ago(45), actor: "julia.andrade@crjsystems.com", event: "ticket.assigned", target: "TCK-2841 → Helena Marques", ip: "189.122.04.92", severity: "info" },
  { id: "ev_6", at: ago(60), actor: "system", event: "encryption.key.rotated", target: "vault_prod", ip: "—", severity: "info" },
  { id: "ev_7", at: ago(120), actor: "bruno.lima@crjsystems.com", event: "customer.export.attempted", target: "c_001 (denied)", ip: "189.122.05.21", severity: "critical" },
  { id: "ev_8", at: ago(180), actor: "system", event: "auth.failed_login", target: "unknown@—", ip: "201.45.221.18", severity: "warning" },
  { id: "ev_9", at: ago(240), actor: "helena.marques@crjsystems.com", event: "session.started", target: "MFA verified", ip: "189.122.04.11", severity: "info" },
  { id: "ev_10", at: ago(360), actor: "system", event: "data_retention.purge", target: "2,840 records (>180d)", ip: "—", severity: "info" },
];

export const ACTIVE_SESSIONS = [
  { id: "s1", device: "MacBook Pro · Chrome 132", location: "São Paulo, BR", ip: "189.122.04.11", lastActive: "now", current: true },
  { id: "s2", device: "iPhone 15 · Safari Mobile", location: "São Paulo, BR", ip: "189.122.04.11", lastActive: "2h ago", current: false },
  { id: "s3", device: "Windows · Edge 121", location: "Rio de Janeiro, BR", ip: "187.49.221.08", lastActive: "1d ago", current: false },
];
